// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpn4rB1DDacu86jC-UmBXbK49Fkq6Doz0',
    appId: '1:1004117718807:web:fc06e6ea8611bb71bfe952',
    messagingSenderId: '1004117718807',
    projectId: 'water-flow-54850',
    authDomain: 'water-flow-54850.firebaseapp.com',
    databaseURL: 'https://water-flow-54850-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flow-54850.appspot.com',
    measurementId: 'G-5TR33H5PBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmvYHD8e-gqGFaTZ5POBlbuJOlcxUsYE4',
    appId: '1:1004117718807:android:3a56bb489681e361bfe952',
    messagingSenderId: '1004117718807',
    projectId: 'water-flow-54850',
    databaseURL: 'https://water-flow-54850-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flow-54850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFA980epOcBE8iT1C-TFQkgpcLZOmZ-E',
    appId: '1:1004117718807:ios:11d0ca4463cd3d74bfe952',
    messagingSenderId: '1004117718807',
    projectId: 'water-flow-54850',
    databaseURL: 'https://water-flow-54850-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flow-54850.appspot.com',
    iosBundleId: 'com.example.nrw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMFA980epOcBE8iT1C-TFQkgpcLZOmZ-E',
    appId: '1:1004117718807:ios:11d0ca4463cd3d74bfe952',
    messagingSenderId: '1004117718807',
    projectId: 'water-flow-54850',
    databaseURL: 'https://water-flow-54850-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flow-54850.appspot.com',
    iosBundleId: 'com.example.nrw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpn4rB1DDacu86jC-UmBXbK49Fkq6Doz0',
    appId: '1:1004117718807:web:32151452d334a16bbfe952',
    messagingSenderId: '1004117718807',
    projectId: 'water-flow-54850',
    authDomain: 'water-flow-54850.firebaseapp.com',
    databaseURL: 'https://water-flow-54850-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-flow-54850.appspot.com',
    measurementId: 'G-Q0BHGS9SC4',
  );
}
